### ISSUE TITLE
valid_encrypted.json Has Poor Metadata

### ISSUE THREAD

**Issue by nickboucher** [microsoft/ElectionGuard-SDK-Reference-Verifier#6]
## Generic Issue

**Description**
*tests/valid_encrypted.json* contains repeated values such as "today'' for *date*, "now" for *time*, and "here" for location. This behavior sets a bad example. Dates, times, and locations should be in valid standard formats that are ideally verified by the verifier.

**Possible Solution**
Improve the example data in *tests/valid_encrypted.json*.

**Comment by echumley-msft** [comment]
Hi, thanks for raising this issue - we've recently transitioned the primary ElectionGuard reference implementation to the [ElectionGuard-Python](https://github.com/microsoft/electionguard-python) repository. The team believes this issue has been resolved or mitigated there, so closing this issue for now as this repository will no longer be actively maintained. Please feel free to check and leave comments in the latest [repo](https://github.com/microsoft/electionguard-python).
