### ISSUE TITLE
Verifier Does Not Compute Extended Base Hash

### ISSUE THREAD

**Issue by nickboucher** [microsoft/ElectionGuard-SDK-Reference-Verifier#7]
The verifier implementation does not compute the extended base hash ad instead defaults to zero; without this, the verifier is incomplete.

See the [TODO](https://github.com/microsoft/electionguard-verifier/blob/master/src/check.rs#L310) in the verifier implementation for missing code.

**Comment by echumley-msft** [comment]
Hi, thanks for raising this issue - we've recently transitioned the primary ElectionGuard reference implementation to the [ElectionGuard-Python](https://github.com/microsoft/electionguard-python) repository. The team believes this issue has been resolved or mitigated there, so closing this issue for now as this repository will no longer be actively maintained. Please feel free to check and leave comments in the latest [repo](https://github.com/microsoft/electionguard-python).
