### ISSUE TITLE
Add Reference to Deserialization Generator

### ISSUE THREAD

**Issue by nickboucher** [microsoft/ElectionGuard-SDK-Reference-Verifier#8]
For many developers writing independent verifiers, this repository will be their first point of reference for information about how to begin their implementation. In another [repository](https://github.com/microsoft/ElectionGuard-SDK-Specification/tree/master/Formal/schema#code-generation), there are instructions about how to automatically generate JSON deserilaization code in your target language of choice for the ElectionGuard JSON format. Including this link in the README for this repository will help to save developers the time and headache of deserializing the election data.

Link: [https://github.com/microsoft/ElectionGuard-SDK-Specification/tree/master/Formal/schema#code-generation](https://github.com/microsoft/ElectionGuard-SDK-Specification/tree/master/Formal/schema#code-generation)

**Comment by echumley-msft** [comment]
Hi, thanks for raising this issue - we've recently transitioned the primary ElectionGuard reference implementation to the [ElectionGuard-Python](https://github.com/microsoft/electionguard-python) repository. The team believes this issue has been resolved or mitigated there, so closing this issue for now as this repository will no longer be actively maintained. Additional information regarding verifiers will be posted there shortly as well. Please feel free to check and leave comments in the latest [repo](https://github.com/microsoft/electionguard-python).
