### ISSUE TITLE
Switch the verifier to use a prime-order subgroup

### ISSUE THREAD

**Issue by keithrfung** [microsoft/ElectionGuard-SDK-Reference-Verifier#9]
## Generic Issue

**Description**
Switch the verifier to use a prime-order subgroup for exponents, as specified in the final version of the ElectionGuard spec. (Current master instead uses the group mod p-1, as specified in a previous draft of the spec.) The primes used in this branch are the same ones from the encryption SDK (specifically bignum.c).

**Comment by echumley-msft** [comment]
The team believes this issue has been resolved or mitigated in the latest [repo](https://github.com/microsoft/electionguard-python).
